//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSFePI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WMSFePI.WMSFePISoap")]
    public interface WMSFePISoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPackingSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WMSFePI.getPackingSearchResponseGetPackingSearchResult> getPackingSearchAsync(string instance, int IO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPIConfig", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WMSFePI.getPIConfigResponseGetPIConfigResult> getPIConfigAsync(string instance, int siID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurrentVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getCurrentVersionAsync(string instance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPIRec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WMSFePI.PI> getPIRecAsync(string instance, int packingID, string labelType, int packHeaderID, string mpn, string lotNumber, string mpnString, string qtyString, string cpnString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WMSFePI.ReturnFEInsertTransaction> updatePIAsync(string instance, int lineID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPIDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WMSFePI.getPIDetailResponseGetPIDetailResult> getPIDetailAsync(string instance, int packingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validatePI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WMSFePI.ReturnFEInsertTransaction> validatePIAsync(string instance, int packingID, int userID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class getPackingSearchResponseGetPackingSearchResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnFEInsertTransaction
    {
        
        private int statusIDField;
        
        private string statusFlagField;
        
        private int interfaceStatusIDField;
        
        private string interfaceStatusFlagField;
        
        private string rcvLineIDField;
        
        private int remainderField;
        
        private int preAddedQtyField;
        
        private int interfaceLStatusIDField;
        
        private string interfaceLStatusFlagField;
        
        private string rcvIDField;
        
        private int isHoldField;
        
        private int flagField;
        
        private int setIDField;
        
        private int requestIDField;
        
        private int remainField;
        
        private int accumulateField;
        
        private int tokenField;
        
        private int onHandQtyField;
        
        private int tokenReturnField;
        
        private int packingIDField;
        
        private int packLineIDField;
        
        private int rankingField;
        
        private string siNumberField;
        
        private int detailIDField;
        
        private int locatorIDField;
        
        private string locatorField;
        
        private string subinventoryField;
        
        private int itemIDField;
        
        private int csiIDField;
        
        private int lineIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusID
        {
            get
            {
                return this.statusIDField;
            }
            set
            {
                this.statusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusFlag
        {
            get
            {
                return this.statusFlagField;
            }
            set
            {
                this.statusFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int InterfaceStatusID
        {
            get
            {
                return this.interfaceStatusIDField;
            }
            set
            {
                this.interfaceStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InterfaceStatusFlag
        {
            get
            {
                return this.interfaceStatusFlagField;
            }
            set
            {
                this.interfaceStatusFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RcvLineID
        {
            get
            {
                return this.rcvLineIDField;
            }
            set
            {
                this.rcvLineIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Remainder
        {
            get
            {
                return this.remainderField;
            }
            set
            {
                this.remainderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PreAddedQty
        {
            get
            {
                return this.preAddedQtyField;
            }
            set
            {
                this.preAddedQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int InterfaceLStatusID
        {
            get
            {
                return this.interfaceLStatusIDField;
            }
            set
            {
                this.interfaceLStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string InterfaceLStatusFlag
        {
            get
            {
                return this.interfaceLStatusFlagField;
            }
            set
            {
                this.interfaceLStatusFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RcvID
        {
            get
            {
                return this.rcvIDField;
            }
            set
            {
                this.rcvIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int IsHold
        {
            get
            {
                return this.isHoldField;
            }
            set
            {
                this.isHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int SetID
        {
            get
            {
                return this.setIDField;
            }
            set
            {
                this.setIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int Remain
        {
            get
            {
                return this.remainField;
            }
            set
            {
                this.remainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Accumulate
        {
            get
            {
                return this.accumulateField;
            }
            set
            {
                this.accumulateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int OnHandQty
        {
            get
            {
                return this.onHandQtyField;
            }
            set
            {
                this.onHandQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int TokenReturn
        {
            get
            {
                return this.tokenReturnField;
            }
            set
            {
                this.tokenReturnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int PackingID
        {
            get
            {
                return this.packingIDField;
            }
            set
            {
                this.packingIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int PackLineID
        {
            get
            {
                return this.packLineIDField;
            }
            set
            {
                this.packLineIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int Ranking
        {
            get
            {
                return this.rankingField;
            }
            set
            {
                this.rankingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string SiNumber
        {
            get
            {
                return this.siNumberField;
            }
            set
            {
                this.siNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int DetailID
        {
            get
            {
                return this.detailIDField;
            }
            set
            {
                this.detailIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int LocatorID
        {
            get
            {
                return this.locatorIDField;
            }
            set
            {
                this.locatorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Locator
        {
            get
            {
                return this.locatorField;
            }
            set
            {
                this.locatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Subinventory
        {
            get
            {
                return this.subinventoryField;
            }
            set
            {
                this.subinventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int ItemID
        {
            get
            {
                return this.itemIDField;
            }
            set
            {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int CsiID
        {
            get
            {
                return this.csiIDField;
            }
            set
            {
                this.csiIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int LineID
        {
            get
            {
                return this.lineIDField;
            }
            set
            {
                this.lineIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PI
    {
        
        private int lineIdField;
        
        private string cPNField;
        
        private string mPNField;
        
        private int qTYField;
        
        private int statusIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LineId
        {
            get
            {
                return this.lineIdField;
            }
            set
            {
                this.lineIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CPN
        {
            get
            {
                return this.cPNField;
            }
            set
            {
                this.cPNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MPN
        {
            get
            {
                return this.mPNField;
            }
            set
            {
                this.mPNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int QTY
        {
            get
            {
                return this.qTYField;
            }
            set
            {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int StatusID
        {
            get
            {
                return this.statusIDField;
            }
            set
            {
                this.statusIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class getPIConfigResponseGetPIConfigResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class getPIDetailResponseGetPIDetailResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WMSFePISoapChannel : WMSFePI.WMSFePISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WMSFePISoapClient : System.ServiceModel.ClientBase<WMSFePI.WMSFePISoap>, WMSFePI.WMSFePISoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WMSFePISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WMSFePISoapClient.GetBindingForEndpoint(endpointConfiguration), WMSFePISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMSFePISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WMSFePISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMSFePISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WMSFePISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMSFePISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Threading.Tasks.Task<WMSFePI.getPackingSearchResponseGetPackingSearchResult> getPackingSearchAsync(string instance, int IO)
        {
            return base.Channel.getPackingSearchAsync(instance, IO);
        }
        
        public System.Threading.Tasks.Task<WMSFePI.getPIConfigResponseGetPIConfigResult> getPIConfigAsync(string instance, int siID)
        {
            return base.Channel.getPIConfigAsync(instance, siID);
        }
        
        public System.Threading.Tasks.Task<string> getCurrentVersionAsync(string instance)
        {
            return base.Channel.getCurrentVersionAsync(instance);
        }
        
        public System.Threading.Tasks.Task<WMSFePI.PI> getPIRecAsync(string instance, int packingID, string labelType, int packHeaderID, string mpn, string lotNumber, string mpnString, string qtyString, string cpnString)
        {
            return base.Channel.getPIRecAsync(instance, packingID, labelType, packHeaderID, mpn, lotNumber, mpnString, qtyString, cpnString);
        }
        
        public System.Threading.Tasks.Task<WMSFePI.ReturnFEInsertTransaction> updatePIAsync(string instance, int lineID, int userID)
        {
            return base.Channel.updatePIAsync(instance, lineID, userID);
        }
        
        public System.Threading.Tasks.Task<WMSFePI.getPIDetailResponseGetPIDetailResult> getPIDetailAsync(string instance, int packingID)
        {
            return base.Channel.getPIDetailAsync(instance, packingID);
        }
        
        public System.Threading.Tasks.Task<WMSFePI.ReturnFEInsertTransaction> validatePIAsync(string instance, int packingID, int userID)
        {
            return base.Channel.validatePIAsync(instance, packingID, userID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WMSFePISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WMSFePISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WMSFePISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.32.1:8066/WMSFePI.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WMSFePISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.32.1:8066/WMSFePI.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WMSFePISoap,
            
            WMSFePISoap12,
        }
    }
}
